// <auto-generated />
namespace ApiMon.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class nullableMoves : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullableMoves));
        
        string IMigrationMetadata.Id
        {
            get { return "202010231941507_nullableMoves"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
